#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
library(shiny)
library(readr)
library(readxl)
library(ggplot2)
library(dplyr)
library(shinythemes)
library(googlesheets4)



navbarPage("Didone Project",
  theme = "flatly",
  tabPanel(title = "About the app",
           h3("Some useful information"),
           p("This app serves as a tool in the visualization of the data of the Didone Project.
           Information about the project can be found", tags$a(href="https://didone.eu/", "here."), "The app provides different functions
             for data visualization. It is structured as follows:"),
           tags$ul(
             tags$li("Variables: this section contains the description of the variables, a visualization of the data in a table, and graphics
                     of one or more variables, as well as linear regression."), 
             tags$li("Temporal evolution: this section contains three different graphs to the visualize temporal evolution of the variables. The first one represents the
                     temporal evolution in a bar plot, being able to filter per factors. The second one contains the temporal evolution of the structural proportions of the pieces,
                     being also able to filter by factors. The last one serves to visualize such structural proportions in the form of lines.") 
             ), 
           downloadButton("fakedata", "Download here the simulated data for triying the app"),
           br(),
           br(),
           p("Please, it is important to upload the files in their corresponding place. Also, note that the app may take some seconds to upload
             all the data and start functioning. "),
           br(),
          
           fileInput("file_ch", "Upload the Excel containing the data on the changes in key, meter, and tempo for the central sections. ",
                     multiple = FALSE,
                     accept = c(".xlsx")),
           fileInput("file_prop",  "Upload the Excel containing the data on the structural proportions of the pieces. ",
                     multiple = FALSE,
                     accept = c(".xlsx")),
           fileInput("file_sco", "Upload the Excel containing the data on the scoring of the pieces.",
                     multiple = FALSE,
                     accept = c(".xlsx")),
           
           br(),
           splitLayout(
           column(1,img(src = "DIDONE.png", height = 100, width = 100)),
           column(1,img(src = "UCM_Logo.jpg", height = 100, width = 100)),
           column(1,img(src = "ICCMU_Logo.jpg", height = 100, width = 100)),
           column(1,img(src = "acronimo_nombrevertical.png", height = 100, width = 110)),
           column(1,img(src = "ERC_Logo.jpg", height = 100, width = 100)),
           column(1,img(src = "EU_Logo_high-res.jpg", height = 100, width = 150))),
           br()
             
           
    
  ),
  navbarMenu(title = "Variables",
             tabPanel(title = "Variable description",
                      p("The used variables are obtained from the variables included in the required files and through
                        transformations of these. We include a short description of the variables:"), 
                      br(),
                      tags$ul(
                        tags$li("Historical variables for of each observation: Opera, Year, Composer,Act, Scene, City, Country, and Form. "),
                        tags$li(" Dramatic variables for each aria: Character and Character type."),
                        tags$li("Structural variables, indicating the number of measures in each section/subsection of the aria: ",tags$ul(
                                tags$li("Aria as a whole: total."), 
                                tags$li("Sections: A, B, and A'."),
                                tags$li("Subsections: rit1, a1, rit2, a2, rit3, rit4, rit1', a1', rit2', a2', and rit3."))),
                        tags$li("Tonal variables: main key for each section (Key_A and Key_B)."),
                        tags$li("Metric variables: main time signature for each section (TSig_A and TSig_B."),
                        tags$li("Tempo variables: main tempo for each section (Tempo_A and Tempo_B)."),
                        tags$li("Instrumental variables: equal to 1 when the relevant instrument is present in the aria and 0 otherwise. These instruments
                                are flute (fl), oboe (ob), horn (hn), English horn (hn) and trumpet (tp).")
                        
                      )
               
             ),
             tabPanel(title = "Data table", 
                      sidebarLayout(
                        sidebarPanel(
                          checkboxGroupInput("show_vars", "Historical variables",
                                             choices = c("Year"= "Year", 
                                                         "Composer" = "Composer", 
                                                         "City", 
                                                         "Country", 
                                                         "Character", 
                                                         "Character type" = "ChType", 
                                                         "Form"
                                                         
                                                         
                                             ), 
                                             selected = c("Year"= "Year", 
                                                          "Composer" = "Composer", 
                                                          "City", 
                                                          "Country", 
                                                          "Character", 
                                                          "ChType", 
                                                          "Form")
                                             
                                             
                          ),
                          checkboxGroupInput("show_vars_1", "General descriptors",
                                             choices = c("Time signature of A" = "TSig_A",
                                                         "Time signature of B" = "TSig_B", 
                                                         "Key of A" = "Key_A", 
                                                         "Key of B" = "Key_B",
                                                         "Tempo of A" = "Simp_Temp_A",
                                                         "Tempo of B" = "Simp_Temp_B"
                                                         
                                             )
                                             
                                             
                                             
                          ),
                          checkboxGroupInput("show_vars_2", "Sections and subsections in measures", 
                                             choices = c(
                                               "Total duration " = "Total_mm",
                                               "A" = "A",
                                               "B" = "B",
                                               "A'" = "A'",
                                               "Ritornello 1 " = "Rit1",
                                               "a1" = "a1",
                                               "Ritornello 2" = "Rit2",
                                               "a2 (in measures)" = "a2",
                                               "Ritornello 3" = "Rit3",
                                               "Rittornello 1'" = "Rit1'",
                                               "Ritornello 4" = "Rit4",
                                               "a1'" = "a1p",
                                               "Ritornello 2'"= "Rit2'",
                                               "a2' (in measures)" = "a2'",
                                               "Ritornello 3'" = "Rit3'"
                                             )
                            
                          ),
                          checkboxGroupInput("show_vars_3", "Sections and subsections in minutes",
                                             choices = c("Total duration" = "Total_min",
                                                         "A" = "A_min",
                                                         "B" = "B_min",
                                                         "A'" = "Ap_min",
                                                         "Ritornello 1" = "Rit1_min",
                                                         "a1" = "a1_min",
                                                         "Ritornello 2" = "Rit2_min",
                                                         "a2" = "a2_min",
                                                         "Ritornello 3" = "Rit3_min",
                                                         "Ritornello 4" = "min_Rit4",
                                                         "Ritornello 1'" = "min_Rit1p",
                                                         "a1'" = "min_a1p",
                                                         "Ritornello 2'" = "min_Rit2p",
                                                         "a2'" = "min_a2p",
                                                         "Ritornello 3'" = "min_Rit3p"
                                                         
                                                         )
                                             )
                          ),
                        mainPanel(
                          id = 'dataset',
                          h3("Data table"), 
                          DT::dataTableOutput("mytable1")
                        )
                        
                      )
                      
               
             ),
            
        tabPanel("Graphics",
          tabsetPanel(id="Graphics", 
                    type = "tabs",
                    tabPanel(title = "Marginal plot of one variable",
                             
                             sidebarLayout(
                               sidebarPanel(selectInput("allvariables", label = "Select the variable you want to visualize",
                                                        choices = list("Year"= "Year", 
                                                                       "Composer" = "Composer", 
                                                                       "City", 
                                                                       "Country", 
                                                                       "Character", 
                                                                       "Character type" =  "ChType", 
                                                                       "Form", 
                                                                       "Total duration in measures" = "Total_mm",
                                                                       "Total duration in minutes" = "Total_min",
                                                                       `Sections in measures` = c("A"="A", "B", "A'"= "A'"),
                                                                       `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                                                       `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                                       `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min"),
                                                                       "Time signature of A" = "TSig_A",
                                                                       "Time signature of B" = "TSig_B", 
                                                                       "Key of A" = "Key_A", 
                                                                       "Key of B" = "Key_B",
                                                                       "Tempo of A" = "Simp_Temp_A",
                                                                       "Tempo of B" = "Simp_Temp_B",
                                                                       "Flute" = "fl",
                                                                       "Oboe" = "ob",
                                                                       "English horn"="eh",
                                                                       "Horn" = "hn",
                                                                       "Trumpet" = "tpt"),
                                                        
                                                        selected = "Total_mm",
                                                        multiple = FALSE)),
                               mainPanel(plotOutput(
                                 "singleplot"
                               ), 
                               verbatimTextOutput(
                                 "tablecount"
                               )
                                         )
                             )
                             
                             
                    ), 
                    tabPanel(title = "Plot of several variables", 
                             
                             sidebarLayout(
                               sidebarPanel(
                                 radioButtons("optionsplot", "Select how many variables you want to plot", choices = c("Two","Three"), selected = "Two"),
                                 conditionalPanel(condition = "input.optionsplot == 'Two'",
                                   selectInput("var_1", label = "Select one variable",
                                             choices = list("Year"= "Year", 
                                                            "Composer" = "Composer", 
                                                            "City", 
                                                            "Country", 
                                                            "Character", 
                                                            "Character type" =  "ChType", 
                                                            "Form", 
                                                            "Total duration in measures" = "Total_mm",
                                                            "Total duration in minutes" = "Total_min",
                                                            `Sections in measures` = c("A"="A", "B", "A'"= "A'"),
                                                            `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                                            `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                            `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min"),
                                                            "Time signature of A" = "TSig_A",
                                                            "Time signature of B" = "TSig_B", 
                                                            "Key of A" = "Key_A", 
                                                            "Key of B" = "Key_B",
                                                            "Tempo of A" = "Simp_Temp_A",
                                                            "Tempo of B" = "Simp_Temp_B",
                                                            "Flute" = "fl",
                                                            "Oboe" = "ob",
                                                            "English horn"="eh",
                                                            "Horn" = "hn",
                                                            "Trumpet" = "tpt"),
                                             selected = "Composer",
                                             multiple = FALSE),
                                 selectInput("var_2",label = "Select another variable",
                                             choices = list("Year"= "Year", 
                                                            "Composer" = "Composer", 
                                                            "City", 
                                                            "Country", 
                                                            "Character", 
                                                            "Character type" =  "ChType", 
                                                            "Form", 
                                                            "Total duration in measures" = "Total_mm",
                                                            "Total duration in minutes" = "Total_min",
                                                            `Sections in measures` = c("A"="A", "B", "A'"= "A'"),
                                                            `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                                            `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                            `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min"),
                                                            "Time signature of A" = "TSig_A",
                                                            "Time signature of B" = "TSig_B", 
                                                            "Key of A" = "Key_A", 
                                                            "Key of B" = "Key_B",
                                                            "Tempo of A" = "Simp_Temp_A",
                                                            "Tempo of B" = "Simp_Temp_B",
                                                            "Flute" = "fl",
                                                            "Oboe" = "ob",
                                                            "English horn"="eh",
                                                            "Horn" = "hn",
                                                            "Trumpet" = "tpt"),
                                             selected = "Total_mm",
                                             multiple = FALSE
                                 )),
                                 conditionalPanel(condition = "input.optionsplot == 'Three'",
                                                  selectInput("vari_1", label = "Select one variable",
                                                              choices = list("Year"= "Year", 
                                                                             "Composer" = "Composer", 
                                                                             "City", 
                                                                             "Country", 
                                                                             "Character", 
                                                                             "Character type" =  "ChType", 
                                                                             "Form", 
                                                                             "Total duration in measures" = "Total_mm",
                                                                             "Total duration in minutes" = "Total_min",
                                                                             `Sections in measures` = c("A"="A", "B", "A'"= "A'"),
                                                                             `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                                                             `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                                             `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min"),
                                                                             "Time signature of A" = "TSig_A",
                                                                             "Time signature of B" = "TSig_B", 
                                                                             "Key of A" = "Key_A", 
                                                                             "Key of B" = "Key_B",
                                                                             "Tempo of A" = "Simp_Temp_A",
                                                                             "Tempo of B" = "Simp_Temp_B",
                                                                             "Flute" = "fl",
                                                                             "Oboe" = "ob",
                                                                             "English horn"="eh",
                                                                             "Horn" = "hn",
                                                                             "Trumpet" = "tpt"),
                                                              selected = "Country",
                                                              multiple = FALSE),
                                                  selectInput("vari_2",label = "Select another variable",
                                                              choices = list("Year"= "Year", 
                                                                             "Composer" = "Composer", 
                                                                             "City", 
                                                                             "Country", 
                                                                             "Character", 
                                                                             "Character type" =  "ChType", 
                                                                             "Form", 
                                                                             "Total duration in measures" = "Total_mm",
                                                                             "Total duration in minutes" = "Total_min",
                                                                             `Sections in measures` = c("A"="A", "B", "A'"= "A'"),
                                                                             `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                                                             `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                                             `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min"),
                                                                             "Time signature of A" = "TSig_A",
                                                                             "Time signature of B" = "TSig_B", 
                                                                             "Key of A" = "Key_A", 
                                                                             "Key of B" = "Key_B",
                                                                             "Tempo of A" = "Simp_Temp_A",
                                                                             "Tempo of B" = "Simp_Temp_B",
                                                                             "Flute" = "fl",
                                                                             "Oboe" = "ob",
                                                                             "English horn"="eh",
                                                                             "Horn" = "hn",
                                                                             "Trumpet" = "tpt"),
                                                              selected = "Total_mm",
                                                              multiple = FALSE
                                                  ),
                                                  selectInput("vari_3",label = "Select a factor for filling the graph",
                                                              choices = list("Composer" = "Composer", 
                                                                             "City", 
                                                                             "Country", 
                                                                             "Character", 
                                                                             "Character type" =  "ChType", 
                                                                             "Form",
                                                                             "Time signature of A" = "TSig_A",
                                                                             "Time signature of B" = "TSig_B", 
                                                                             "Key of A" = "Key_A", 
                                                                             "Key of B" = "Key_B",
                                                                             "Tempo of A" = "Simp_Temp_A",
                                                                             "Tempo of B" = "Simp_Temp_B",
                                                                             "Flute" = "fl",
                                                                             "Oboe" = "ob",
                                                                             "English horn"="eh",
                                                                             "Horn" = "hn",
                                                                             "Trumpet" = "tpt"),
                                                              selected = "Form",
                                                              multiple = FALSE
                                                  ))
                               ),
                               mainPanel (
                                 conditionalPanel(condition = "input.optionsplot == 'Two'",
                                   plotOutput("CombinedPlot")
                                 ),
                                 conditionalPanel(condition = "input.optionsplot == 'Three'",
                                                  plotOutput("Fillingplot"))
                                 
                                 
                               )
                             )
                             
                             
                    ),
                    tabPanel(title = "Linear regression",
                      sidebarLayout(
                        sidebarPanel(
                          radioButtons("regressions", "Select one or more regressors",
                                       choices = c("Only one numeric regressor"= "1reg", "Multiple regression" = "multreg"), selected = "1reg"),
                          
                          conditionalPanel(condition = "input.regressions == '1reg'",
                                           selectInput("DepVar", "Select the dependent variable",
                                                       choices = list("Year",
                                                                      "Total duration in measures" = "Total_mm",
                                                                      "Total duration in minutes" = "Total_min",
                                                                      `Sections in measures` = c("A"="A", "B", "A'"= "`A'`"),
                                                                      `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                                                      `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                                      `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min")
                                                       ),
                                                       selected = "Total_mm",
                                                       multiple = FALSE
                                           ),
                                           selectInput("IndVar", "Select the independent variable",
                                                       choices = list("Year",
                                                                      "Total duration in measures" = "Total_mm",
                                                                      "Total duration in minutes" = "Total_min",
                                                                      `Sections in measures` = c("A"="A", "B", "A'"= "`A'`"),
                                                                      `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                                                      `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                                      `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min")
                                                                      
                                                       ),
                                                       selected = "A",
                                                       multiple = FALSE), 
                                           selectInput("IndVar2", "Select a factor", 
                                                       choices = c("No factor",
                                                                   "Composer" = "Composer", 
                                                                   "City", 
                                                                   "Country", 
                                                                   "Character", 
                                                                   "Character type" = "ChType", 
                                                                   "Form", 
                                                                   "Time signature of A" = "TSig_A",
                                                                   "Time signature of B" = "TSig_B", 
                                                                   "Key of A" = "Key_A", 
                                                                   "Key of B" = "Key_B",
                                                                   "Flute" = "fl", 
                                                                   "Oboe" = "ob",
                                                                   "English horn" = "eh",
                                                                   "Horn" = "hn",
                                                                   "Trumpet" = "tpt"),
                                                       selected = "Form",
                                                       multiple = FALSE)),
                          conditionalPanel(condition = "input.regressions == 'multreg'",
                                           selectInput("DepVar_", "Select the dependent variable",
                                                       choices = list("Year",
                                                                      "Total duration in measures" = "Total_mm",
                                                                      "Total duration in minutes" = "Total_min",
                                                                      `Sections in measures` = c("A"="A", "B", "A'"= "`A'`"),
                                                                      `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                                                      `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                                      `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min")
                                                       ),
                                                       selected = "Total_mm",
                                                       multiple = FALSE
                                           ),
                                           selectInput("IndVar_", "Select the independent variables",
                                                       choices = list("Year",
                                                                      "Total duration in measures" = "Total_mm",
                                                                      "Total duration in minutes" = "Total_min",
                                                                      `Sections in measures` = c("A"="A", "B", "A'"= "`A'`"),
                                                                      `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                                                      `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                                      `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min")
                                                                      
                                                       ),
                                                       selected = "A",
                                                       multiple = TRUE), 
                                           selectInput("IndVar2_", "Select factor variables", 
                                                       choices = c("Composer" = "Composer", 
                                                                   "City", 
                                                                   "Country", 
                                                                   "Character", 
                                                                   "Character type" = "ChType", 
                                                                   "Form", 
                                                                   "Time signature of A" = "TSig_A",
                                                                   "Time signature of B" = "TSig_B", 
                                                                   "Key of A" = "Key_A", 
                                                                   "Key of B" = "Key_B",
                                                                   "Flute" = "fl", 
                                                                   "Oboe" = "ob",
                                                                   "English horn" = "eh",
                                                                   "Horn" = "hn",
                                                                   "Trumpet" = "tpt"),
                                                       selected = "Form",
                                                       multiple = TRUE))
                        ),
                        
                        mainPanel(
                          conditionalPanel(condition = "input.regressions == '1reg'",
                                          plotOutput("Regression"),
                                          verbatimTextOutput(outputId = "RegSum")), 
                          conditionalPanel(condition = "input.regressions == 'multreg'",
                                           plotOutput("Regression2"),
                                           verbatimTextOutput(outputId = "RegSum2"))
                          
                        )
                      )
                    )
                    
        ))),

  tabPanel(title = "Temporal evolution",
           tabsetPanel(id="evolution",
                       type = "tabs",
                       tabPanel("Bar plot graph",
             
           
           sidebarLayout(
             sidebarPanel(
               radioButtons("years", "Select time range", choices = c("By year", "By decade"), selected = "By year"),
               selectInput("numvar", label = h3("Select the numeric variable"),
                           choices = list("Total duration in measures" = "Total_mm",
                                       "Total duration in minutes" = "Total_min",
                                       `Sections in measures` = c("A"="A", "B", "A'"= "A'"),
                                       `Subsections of A in measures` = c("Rit1", "a1", "Rit2", "a2", "Rit3"),
                                       `Sections in minutes` = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                       `Subsections of A in minutes` = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min")), 
                           multiple = FALSE,
                           selected = "Total_mm"
                           
               ), 
               selectInput("Facvar", label = h3("Select a factor"),
                           choices = c("No factor",
                                       "Composer" = "Composer", 
                                       "City", 
                                       "Country", 
                                       "Character", 
                                       "Character type" = "ChType", 
                                       "Form", 
                                       "Time signature of A" = "TSig_A",
                                       "Time signature of B" = "TSig_B", 
                                       "Key of A" = "Key_A", 
                                       "Key of B" = "Key_B",
                                       "Flute" = "fl", 
                                       "Oboe" = "ob",
                                       "English horn" = "eh",
                                       "Horn" = "hn",
                                       "Trumpet" = "tpt"),
                           multiple = FALSE,
                           selected = "No factor"), 
               conditionalPanel(condition = "input.Facvar == 'Country'",
                                selectInput("country", label=h3("Select a country "),
                                            choices = c("Denmark",
                                                        "Italy", 
                                                        "Empire",
                                                        "Portugal",
                                                        "Spain",
                                                        "France"),
                                            selected = "Italy",
                                            
                                            multiple = FALSE)
                                
               ),
               conditionalPanel(condition = "input.Facvar == 'Composer'",
                                selectInput("comp", label=h3("Select a Composer "),
                                            choices = c("Anfossi",
                                                        "Astarita", 
                                                        "Bernasconi",
                                                        "Boroni",
                                                        "Caldara",
                                                        "Errichelli",
                                                        "Ferradini",
                                                        "Galuppi",
                                                        "Gluck",
                                                        "Graun",
                                                        "Hasse",
                                                        "Jommelli",
                                                        "Kozeluch",
                                                        "Lampugnani",
                                                        "Leo",
                                                        "Majo",
                                                        "Mancini",
                                                        "Manna",
                                                        "Myslevecek",
                                                        "Paer",
                                                        "Paisiello",
                                                        "Perez",
                                                        "Piccinni",
                                                        "Sarro",
                                                        "Sarti",
                                                        "Scalabrini",
                                                        "Schiassi",
                                                        "Schuster",
                                                        "Terradellas",
                                                        "Traetta",
                                                        "Vinci",
                                                        "Viotti",
                                                        "Wagenseil"))
                                
               ),
               conditionalPanel(condition = "input.Facvar == 'City'",
                                selectInput("city", label=h3("Select a city"),
                                            choices = c("Berlin",
                                                        "Bratislava", 
                                                        "Copenhagen",
                                                        "Dresden",
                                                        "Genova",
                                                        "Hamburg",
                                                        "Lisbon",
                                                        "Madrid",
                                                        "Milan",
                                                        "Munich",
                                                        "Naples",
                                                        "Padova",
                                                        "Paris",
                                                        "Prague",
                                                        "Reggio Emilia",
                                                        "Rome",
                                                        "Stuttgart",
                                                        "Turin",
                                                        "Venice",
                                                        "Vienna",
                                                        "Wermsdorf"),
                                            multiple = FALSE, selected = "Naples")
               ),
               conditionalPanel(condition = "input.Facvar == 'Character'",
                                selectInput("charac", label=h3("Select a character"),
                                            choices = c("Adrasto",
                                                        "Alessandro", 
                                                        "Araspe",
                                                        "Cherinto",
                                                        "Cleofide",
                                                        "Cleofide,Poro",
                                                        "Creusa",
                                                        "Demofoonte",
                                                        "Didone",
                                                        "Didone & Enea" = "Didone&Enea",
                                                        "Didone & Enea & Iarba" =  "Didone&Enea&Iarba",
                                                        "Dircea",
                                                        "Dircea & Timante" = "Dircea&Timante",
                                                        "Dircea, Timante" = "Dircea,Timante",
                                                        "Dircea, Timante & Demofoonte" = "Dircea,Timante&Demofoonte",
                                                        "Enea",
                                                        "Erissena",
                                                        "Gandarte",
                                                        "Iarba",
                                                        "Matusio",
                                                        "Osmida",
                                                        "Poro",
                                                        "Selene",
                                                        "Timagene",
                                                        "Timante"),
                                            multiple = FALSE)), 
               conditionalPanel(condition = "input.Facvar == 'ChType'",
                                selectInput("ChType", label=h3("Select a the type of character"),
                                            choices = c("Antagonist",
                                                        "Confidant", 
                                                        "Female lover 1",
                                                        "Female lover1,Male lover 1",
                                                        "Female lover 2",
                                                        "Male lover 1",
                                                        "Male lover 2",
                                                        "Male lover 3",
                                                        "Senior ruler"),
                                            multiple = FALSE)
                                
               ),
               conditionalPanel(condition = "input.Facvar == 'Form'",
                                selectInput("form", label=h3("Select the form "),
                                            choices = c("ABA",
                                                        "ABC", 
                                                        "Al segno",
                                                        "Da capo"),
                                            multiple = FALSE)
                                
               ),
               conditionalPanel(condition = "input.Facvar == 'TSig_A'",
                                selectInput("timeA", label=h3("Select the time signature"),
                                            choices = c("2/4",
                                                        "3/2",
                                                        "3/4",
                                                        "3/8",
                                                        "6/8",
                                                        "C",
                                                        "C|"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.Facvar == 'TSig_B'",
                                selectInput("timeB", label=h3("Select the time signature "),
                                            choices = c("2/4",
                                                        "3/4",
                                                        "3/8",
                                                        "6/8",
                                                        "C",
                                                        "C|"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.Facvar == 'Key_A'",
                                selectInput("key_A", label=h3("Select the key "),
                                            choices = c("a",
                                                        "A",
                                                        "b",
                                                        "Bb",
                                                        "6/8",
                                                        "c",
                                                        "C",
                                                        "d",
                                                        "D",
                                                        "e",
                                                        "E",
                                                        "Eb",
                                                        "f",
                                                        "F",
                                                        "g",
                                                        "G"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.Facvar == 'Key_B'",
                                selectInput("key_B", label=h3("Select the key "),
                                            choices = c("a",
                                                        "A",
                                                        "Ab",
                                                        "b",
                                                        "Bb",
                                                        "BB",
                                                        "c",
                                                        "C",
                                                        "c#",
                                                        "d",
                                                        "D",
                                                        "Db",
                                                        "e",
                                                        "E",
                                                        "Eb",
                                                        "f",
                                                        "F",
                                                        "f#",
                                                        "F#",
                                                        "g",
                                                        "G",
                                                        "g#"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.Facvar == 'fl'",
                                selectInput("flute", label=h3("Flute present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.Facvar == 'ob'",
                                selectInput("oboe", label=h3("Oboe present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE)), 
               conditionalPanel(condition = "input.Facvar == 'eh'",
                                selectInput("enhorn", label=h3("English horn present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.Facvar == 'hn'",
                                selectInput("horn", label=h3("Horn present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.Facvar == 'tpt'",
                                selectInput("trumpet", label=h3("Trumpet present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE))
               
               
               
             ),
             mainPanel( conditionalPanel(condition = "input.years == 'By year'", 
                                         plotOutput("Graph")),
                        conditionalPanel(condition = "input.years == 'By decade'", 
                                         plotOutput("Graph_2"))
               
              
             )
             
           
             
           )
           ),
  tabPanel(title = "Proportions plot", 
           sidebarLayout(
             sidebarPanel(
               radioButtons("pr", "Choose a dataset",
                            c("A, B & A' in measures" = "ABA",
                              "A, B & A' in minutes" = "ABAmin",
                              "Subsections of A in measures" = "Ac",
                              "Subsections of A in minutes" = "Am")
                            
               ),
               selectInput("condition", label = h3("Select a factor"),
                           choices = c("General",
                                       "Composer" = "Composer", 
                                       "City", 
                                       "Country", 
                                       "Character", 
                                       "Character type" = "ChType", 
                                       "Form", 
                                       "Time signature of A" = "TSig_A",
                                       "Time signature of B" = "TSig_B", 
                                       "Key of A" = "Key_A", 
                                       "Key of B" = "Key_B",
                                       "Tempo of A" = "Simp_Temp_A",
                                       "Tempo of B" = "Simp_Temp_B",
                                       "Flute" = "fl", 
                                       "Oboe" = "ob",
                                       "English horn" = "eh",
                                       "Horn" = "hn",
                                       "Trumpet" = "tpt"),
                           multiple = FALSE,
                           selected = "General"),
               conditionalPanel(condition = "input.condition == 'Country'",
                                selectInput("country_1", label=h3("Select a country "),
                                            choices = c("Denmark",
                                                        "Italy", 
                                                        "Empire",
                                                        "Portugal",
                                                        "Spain",
                                                        "France"),
                                            selected = "Italy",
                                            
                                            multiple = FALSE)
                                
               ),
               conditionalPanel(condition = "input.condition == 'Composer'",
                                selectInput("comp_1", label=h3("Select a Composer "),
                                            choices = c("Anfossi",
                                                        "Astarita", 
                                                        "Bernasconi",
                                                        "Boroni",
                                                        "Caldara",
                                                        "Errichelli",
                                                        "Ferradini",
                                                        "Galuppi",
                                                        "Gluck",
                                                        "Graun",
                                                        "Hasse",
                                                        "Jommelli",
                                                        "Kozeluch",
                                                        "Lampugnani",
                                                        "Leo",
                                                        "Majo",
                                                        "Mancini",
                                                        "Manna",
                                                        "Myslevecek",
                                                        "Paer",
                                                        "Paisiello",
                                                        "Perez",
                                                        "Piccinni",
                                                        "Sarro",
                                                        "Sarti",
                                                        "Scalabrini",
                                                        "Schiassi",
                                                        "Schuster",
                                                        "Terradellas",
                                                        "Traetta",
                                                        "Vinci",
                                                        "Viotti",
                                                        "Wagenseil"))
                                
               ),
               conditionalPanel(condition = "input.condition == 'City'",
                                selectInput("city_1", label=h3("Select a city"),
                                            choices = c("Berlin",
                                                        "Bratislava", 
                                                        "Copenhagen",
                                                        "Dresden",
                                                        "Genova",
                                                        "Hamburg",
                                                        "Lisbon",
                                                        "Madrid",
                                                        "Milan",
                                                        "Munich",
                                                        "Naples",
                                                        "Padova",
                                                        "Paris",
                                                        "Prague",
                                                        "Reggio Emilia",
                                                        "Rome",
                                                        "Stuttgart",
                                                        "Turin",
                                                        "Venice",
                                                        "Vienna",
                                                        "Wermsdorf"),
                                            multiple = FALSE, selected = "Naples")
               ),
               conditionalPanel(condition = "input.condition == 'Character'",
                                selectInput("charac_1", label=h3("Select a character"),
                                            choices = c("Adrasto",
                                                        "Alessandro", 
                                                        "Araspe",
                                                        "Cherinto",
                                                        "Cleofide",
                                                        "Cleofide,Poro",
                                                        "Creusa",
                                                        "Demofoonte",
                                                        "Didone",
                                                        "Didone & Enea" = "Didone&Enea",
                                                        "Didone & Enea & Iarba" =  "Didone&Enea&Iarba",
                                                        "Dircea",
                                                        "Dircea & Timante" = "Dircea&Timante",
                                                        "Dircea, Timante" = "Dircea,Timante",
                                                        "Dircea, Timante & Demofoonte" = "Dircea,Timante&Demofoonte",
                                                        "Enea",
                                                        "Erissena",
                                                        "Gandarte",
                                                        "Iarba",
                                                        "Matusio",
                                                        "Osmida",
                                                        "Poro",
                                                        "Selene",
                                                        "Timagene",
                                                        "Timante"),
                                            multiple = FALSE)), 
               conditionalPanel(condition = "input.condition == 'ChType'",
                                selectInput("type_1", label=h3("Select the type of character "),
                                            choices = c("Antagonist",
                                                        "Confidant", 
                                                        "Female lover 1",
                                                        "Female lover1,Male lover 1",
                                                        "Female lover 2",
                                                        "Male lover 1",
                                                        "Male lover 2",
                                                        "Male lover 3",
                                                        "Senior ruler"),
                                            multiple = FALSE)
                                
               ),
               conditionalPanel(condition = "input.condition == 'Form'",
                                selectInput("form_1", label=h3("Select the form "),
                                            choices = c("ABA",
                                                        "ABC", 
                                                        "Al segno",
                                                        "Da capo"),
                                            multiple = FALSE)
                                
               ),
               conditionalPanel(condition = "input.condition == 'TSig_A'",
                                selectInput("timeA_1", label=h3("Select the time signature "),
                                            choices = c("2/4",
                                                        "3/2",
                                                        "3/4",
                                                        "3/8",
                                                        "6/8",
                                                        "C",
                                                        "C|"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.condition == 'TSig_B'",
                                selectInput("timeB_1", label=h3("Select the time signature"),
                                            choices = c("2/4",
                                                        "3/4",
                                                        "3/8",
                                                        "6/8",
                                                        "C",
                                                        "C|"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.condition == 'Key_A'",
                                selectInput("key_A_1", label=h3("Select the key "),
                                            choices = c("a",
                                                        "A",
                                                        "b",
                                                        "Bb",
                                                        "6/8",
                                                        "c",
                                                        "C",
                                                        "d",
                                                        "D",
                                                        "e",
                                                        "E",
                                                        "Eb",
                                                        "f",
                                                        "F",
                                                        "g",
                                                        "G"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.condition == 'Key_B'",
                                selectInput("key_B_1", label=h3("Select the key "),
                                            choices = c("a",
                                                        "A",
                                                        "Ab",
                                                        "b",
                                                        "Bb",
                                                        "BB",
                                                        "c",
                                                        "C",
                                                        "c#",
                                                        "d",
                                                        "D",
                                                        "Db",
                                                        "e",
                                                        "E",
                                                        "Eb",
                                                        "f",
                                                        "F",
                                                        "f#",
                                                        "F#",
                                                        "g",
                                                        "G",
                                                        "g#"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.condition == 'fl'",
                                selectInput("flute_1", label=h3("Flute present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.condition == 'ob'",
                                selectInput("oboe_1", label=h3("Oboe present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE)), 
               conditionalPanel(condition = "input.condition == 'eh'",
                                selectInput("enhorn_1", label=h3("English horn present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.condition == 'hn'",
                                selectInput("horn_1", label=h3("Horn present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE)),
               conditionalPanel(condition = "input.condition == 'tpt'",
                                selectInput("trumpet_1", label=h3("Trumpet present:"),
                                            choices = c("Yes" = "1",
                                                        "No" = "0"),
                                            multiple = FALSE))
             ),
             
             
             mainPanel(
               plotOutput("generalg", height = "18cm"), 
               plotOutput("generaldec")
             )
           )
           
             ),
  tabPanel(title = "Evolution in lines",
           sidebarLayout(
             sidebarPanel(
               radioButtons("options", "In measures or minutes", 
                            choices = c("Measures","Minutes"),
                            selected = "Measures"),
               conditionalPanel(condition = "input.options == 'Measures'",
               selectInput("section_m", label = "Select one or more sections",
                           choices = list("Total measures"="Total_mm",
                             Sections = c("A"= "A", "B", "A'"= "A'"),
                                          Subsections = c("Rit1", "a1", "Rit2", "a2", "Rit3")
                             
                           ), selected = "A", multiple = TRUE)),
               conditionalPanel(condition = "input.options == 'Minutes'", 
                                selectInput("section_min",label = "Select one or more sections",
                                            choices =  list("Total minutes"="Total_min",
                                                                     Sections = c("A"= "A_min", "B" = "B_min", "A'"= "Ap_min"),
                                                                     Subsections = c("Rit1" = "Rit1_min" , "a1" = "a1_min", "Rit2" = "Rit2_min", "a2" = "a2_min", "Rit3" = "Rit3_min")),
                                            selected = "Total_min", multiple = TRUE))
             ), 
             mainPanel(conditionalPanel(condition = "input.options == 'Measures'",
                                        plotOutput("linesmeasures")),
                       conditionalPanel(condition = "input.options == 'Minutes'",
                                        plotOutput("linesminutes")))
           ))
             
           
           ))
  )









